name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install HuggingFace Hub CLI
        run: pip install huggingface_hub

      - name: Upload to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.TeamCareerProgressionAppTOKEN }}
        run: |
          hf upload \
            Priyanka-Ankam/Team-Progression-App \
            . \
            --token $HF_TOKEN \
            --commit-message "Auto deploy to HF from GitHub"
