name: Deploy to Hugging Face Space

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Upload project to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.TEAMCAREERPROGRESSIONAPPTOKEN }}
        run: |
          hf upload \
            Priyanka-Ankam/Team-Progression-App \
            . \
            --token $HF_TOKEN \
            --commit-message "GitHub â†’ HF Auto Deploy"
